### ISSUE TITLE
User story: Create and manage student profiles

### ISSUE THREAD

**Issue by Chockeh** [Chockeh/SnakeTeam-soen341project2023#20]
**As a** Student **I want to** create and manage my student profile **because** a student profile must display professional information pertinent to employers.

**Story point:** 3

**Task Breakdown:**

- Upload a picture.
- Upload resume.
- Create an “About” section.
- Create a “Job Experience” section.
- Create an “Education” section.
- Create a “Skills” section.
- Create a “Projects” section.
- Create an “External Links” section.

**Validation Test:**

- Create a profile and fill in all sections.
- Upload a profile photo.
- Upload resume.

**Risks:**

- The profile photo is of the wrong file type.
- The resume is of the wrong file type.

**Countermeasures:**

- Display "wrong file type" for the profile photo.
- Display "wrong file type" for the resume.

**Comment by Chockeh** [comment]
Did not implement the "upload picture" and "upload resume" features.

**Comment by Chockeh** [comment]
Added the ability to upload resumes and profiles in Sprint 3.

**Comment by ey-meh** [comment]
We did the frontend and backend, we are just not sure about the submit button. @Sisahga can you test on MongoDB

**Comment by Chockeh** [comment]
Re-opened for Sprint 4.

**Comment by Sisahga** [comment]
Resume part is complete, not the picture feature.
