### ISSUE TITLE
User story: Suggest a job posting to a student

### ISSUE THREAD

**Issue by Chockeh** [Chockeh/SnakeTeam-soen341project2023#27]
**As a** Guide **I want to** suggest a job posting to a student **because** the role of the guide is to link employers and students. 

**Story Point:** 2

**Task Breakdown:**

- Browse student profiles.
- Suggest a job posting to a student.

**Validation Test:**

- Browse an existing student profile.
- Analyze their qualifications.
- Suggest job postings relevant to that student.

**Risks:**

- Cannot browse student profiles.

**Countermeasures:**

- Report to the administrator that there is a problem.

**Comment by Chockeh** [comment]
Moved to Sprint 4.

**Comment by Sisahga** [comment]
Completed
