### ISSUE TITLE
Write acceptance tests

### ISSUE THREAD

**Issue by Chockeh** [Chockeh/SnakeTeam-soen341project2023#37]
Create acceptance tests for core and additional features:

Core features:
1. Browsing for available job postings
2. Adding and managing postings by the employer
3. Students applying to job postings and receive a notification when selected
4. Creating and managing student profiles

Additional features:
1. User ratings
2. Guide suggests edits to student profiles
3. Guide suggests job postings to a student
4. Guide link students to Udemy courses

**Comment by Sisahga** [comment]
Acceptance tests not complete.
